[package]
name = "ddnet-engine-client"
version = "0.0.1"
edition = "2021"
publish = false
license = "Zlib"

[lib]
crate-type = ["rlib", "staticlib"]
path = "lib.rs"

[dependencies]
ddnet-base = { path = "../../base" }
ddnet-engine = { path = ".." }

bytemuck = "1.22.0"
cxx = "1.0"
pollster = "0.4.0"
wgpu = "24.0.1"

[dev-dependencies]
ddnet-test = { path = "../../rust-bridge/test", features = ["link-test-libraries"] }
